# Generated by Django 3.0.5 on 2020-04-26 10:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('cvv', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('items', models.CharField(default='item1', max_length=255)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authen.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=255)),
                ('description', models.CharField(default='desc', max_length=255)),
                ('release_date', models.DateTimeField(default=datetime.datetime(2020, 4, 26, 10, 5, 42, 606580))),
                ('rating', models.IntegerField(default=5)),
                ('price', models.IntegerField(default=100)),
                ('image', models.CharField(default='image', max_length=255)),
                ('num_pages', models.SmallIntegerField()),
                ('format', models.CharField(choices=[('HC', 'Hard Cover'), ('SC', 'Soft Cover')], max_length=2)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Author')),
                ('category', models.ManyToManyField(to='main.Categories')),
                ('genre', models.ManyToManyField(to='main.Genre')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Publisher')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=255)),
                ('description', models.CharField(default='desc', max_length=255)),
                ('release_date', models.DateTimeField(default=datetime.datetime(2020, 4, 26, 10, 5, 42, 606580))),
                ('rating', models.IntegerField(default=5)),
                ('price', models.IntegerField(default=100)),
                ('image', models.CharField(default='image', max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Author')),
                ('category', models.ManyToManyField(to='main.Categories')),
                ('genre', models.ManyToManyField(to='main.Genre')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Review')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
