# Generated by Django 3.0.5 on 2020-04-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='todo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='todo'),
        ),
    ]
