# Generated by Django 3.0.5 on 2020-04-26 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 10, 55, 59, 970980)),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 10, 55, 59, 970980)),
        ),
    ]
