# Generated by Django 3.0.4 on 2020-04-01 18:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_auto_20200401_1827'),
        ('main', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('bookbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.BookBase')),
                ('duration', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
            ],
            bases=('main.bookbase',),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='bookbase',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Author'),
        ),
        migrations.AddField(
            model_name='bookbase',
            name='description',
            field=models.CharField(default='desc', max_length=255),
        ),
        migrations.AddField(
            model_name='bookbase',
            name='genre',
            field=models.ManyToManyField(to='main.Genre'),
        ),
        migrations.AddField(
            model_name='bookbase',
            name='image',
            field=models.CharField(default='image', max_length=255),
        ),
        migrations.AddField(
            model_name='bookbase',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='bookbase',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='bookbase',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 18, 27, 49, 779318, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='bookbase',
            name='reviews',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Review'),
        ),
        migrations.AddField(
            model_name='bookbase',
            name='title',
            field=models.CharField(default='title', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.CharField(default='item1', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authen.MyUser'),
        ),
        migrations.AddField(
            model_name='bookbase',
            name='category',
            field=models.ManyToManyField(to='main.Categories'),
        ),
    ]
