# Generated by Django 3.0.4 on 2020-04-01 18:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200401_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookbase',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 18, 30, 7, 291814, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bookbase',
            name='reviews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Review'),
        ),
    ]
