# Generated by Django 3.0.4 on 2020-04-01 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200401_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookbase',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 18, 38, 40, 737527, tzinfo=utc)),
        ),
    ]
