# Generated by Django 3.0.5 on 2020-04-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='card_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Card'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order'),
        ),
    ]
