# Generated by Django 3.0.5 on 2020-04-26 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('authen', '0002_auto_20200426_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='card_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Card'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Order'),
        ),
    ]
