# Generated by Django 3.0.4 on 2020-04-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_myuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='order',
            new_name='orders',
        ),
    ]
